name: Build Test
on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v4
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
      - name: Install dependencies
        run: bun install
      - name: Lint App
        run: bun run lint
      - name: Test App
        run: bun run test
      - name: Build App
        run: bun run build
