name: CI
on:
  workflow_dispatch:
  pull_request:
    types: [opened, edited, reopened]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Lint App
        run: npm run lint
      - name: Test App
        run: npm run test
      - name: Build App
        run: npm run build
